begin;
create extension if not exists pgtap;
select plan(20);
select has_table('public','profiles','profiles 테이블');
select has_table('public','attendance_logs','attendance_logs 테이블');
select has_table('public','monthly_reports','monthly_reports 테이블');
select has_table('public','submission_periods','submission_periods 테이블');
select has_table('public','notifications','notifications 테이블');
select has_function('public','is_admin',array[]::text[],'관리자 권한 함수');
select has_function('public','submit_monthly_report',array['uuid'],'제출 RPC');
select has_function('public','review_monthly_report',array['uuid','report_status','text'],'검토 RPC');
select has_function('public','resend_submission_reminder',array['uuid','text'],'Reminder RPC');
select has_function('public','get_admin_dashboard',array['text'],'대시보드 RPC');
select col_is_pk('public','profiles','id','profiles 기본 키');
select col_not_null('public','attendance_logs','student_id','출근 기록 학생 필수');
select col_not_null('public','monthly_reports','year_month','리포트 월 필수');
select policies_are('public','notifications',array['notifications_select','notifications_read'],'알림 RLS 정책');
select table_privs_are('authenticated','public','profiles',array['SELECT'],'authenticated profiles 최소 권한');
select table_privs_are('authenticated','public','attendance_logs',array['DELETE','INSERT','SELECT','UPDATE'],'authenticated attendance 권한');
select table_privs_are('authenticated','public','monthly_reports',array['SELECT','UPDATE'],'authenticated reports 최소 권한');
select table_privs_are('authenticated','public','submission_periods',array['DELETE','INSERT','SELECT','UPDATE'],'submission period RLS용 권한');
select has_column_privilege('authenticated','public','notifications','is_read','UPDATE','알림 읽음 컬럼 수정 권한');
select has_table_privilege('authenticated','public','notifications','SELECT','알림 조회 권한');
select * from finish();
rollback;
