export const Role = { STUDENT:'STUDENT', ADMIN:'ADMIN' };
export const AttendanceStatus = { PRESENT:'PRESENT', LATE:'LATE', ABSENT:'ABSENT', VACATION:'VACATION' };
export const ReportStatus = { NOT_STARTED:'NOT_STARTED', WRITING:'WRITING', SUBMITTED:'SUBMITTED', APPROVED:'APPROVED', REJECTED:'REJECTED' };
export const NotificationType = { REMINDER:'REMINDER', SUBMITTED:'SUBMITTED', APPROVED:'APPROVED', REJECTED:'REJECTED' };
