begin;

-- RLS policies only filter rows after PostgreSQL table privileges allow the
-- operation. The initial migration created the policies but did not grant the
-- authenticated role the table privileges used by the application.
grant usage on schema public to authenticated;

grant select on table public.profiles to authenticated;

grant select, insert, update, delete
  on table public.attendance_logs
  to authenticated;

grant select, update
  on table public.monthly_reports
  to authenticated;

grant select, insert, update, delete
  on table public.submission_periods
  to authenticated;

grant select
  on table public.notifications
  to authenticated;

-- Profiles are authoritative school/internship records. Keep direct writes
-- disabled until they are exposed through a dedicated, validated API/RPC.
revoke insert, update, delete on table public.profiles from authenticated;

-- Monthly report rows are provisioned by database triggers. Clients update an
-- existing row; they must not create or delete arbitrary report records.
revoke insert, delete on table public.monthly_reports from authenticated;

-- Notifications are generated by the backend. A user may only mark their own
-- notification as read (the existing RLS policy still applies).
revoke insert, delete, update on table public.notifications from authenticated;
grant update(is_read) on table public.notifications to authenticated;

commit;
